"""Tests for brain/hooks.py — hook matching, command execution, timeouts."""

import os
import sys
import unittest
from unittest.mock import patch, MagicMock

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from brain.hooks import HooksManager, HookResult


class TestHooksNoHooks(unittest.TestCase):
    """Behavior when no hooks are configured."""

    def test_no_hooks_allows_all(self):
        hm = HooksManager()
        result = hm.run_pre_tool_use("bash", {"command": "rm -rf /"})
        self.assertTrue(result.allowed)

        result = hm.run_post_tool_use("bash", {}, "some output")
        self.assertTrue(result.allowed)

        result = hm.run_stop()
        self.assertTrue(result.allowed)

    def test_has_hooks_false(self):
        hm = HooksManager()
        self.assertFalse(hm.has_hooks)


class TestMatcher(unittest.TestCase):
    """Tests for the _matches() method."""

    def setUp(self):
        self.hm = HooksManager()

    def test_matcher_exact(self):
        self.assertTrue(self.hm._matches("bash", "bash"))
        self.assertFalse(self.hm._matches("bash", "edit_file"))

    def test_matcher_pipe_pattern(self):
        """Pipe-separated patterns should match any alternative."""
        self.assertTrue(self.hm._matches("Edit|Write", "Edit"))
        self.assertTrue(self.hm._matches("Edit|Write", "Write"))
        self.assertFalse(self.hm._matches("Edit|Write", "bash"))

    def test_matcher_prefix_wildcard(self):
        """Patterns ending with * should match prefixes."""
        self.assertTrue(self.hm._matches("web_*", "web_search"))
        self.assertTrue(self.hm._matches("web_*", "web_fetch"))
        self.assertFalse(self.hm._matches("web_*", "bash"))

    def test_matcher_empty(self):
        """Empty matcher matches everything (startswith empty string is always True).

        In practice, _run_hooks skips hooks with empty matchers before calling
        _matches, so this is a documentation test of the raw method behavior.
        """
        # Empty string is a prefix of every string, so _matches returns True
        self.assertTrue(self.hm._matches("", "bash"))


class TestCommandHooks(unittest.TestCase):
    """Tests for command-type hook execution using mocked subprocess."""

    def setUp(self):
        self.hm = HooksManager()

    @patch("brain.hooks.subprocess.run")
    def test_command_hook_allow(self, mock_run):
        """Exit code 0 should allow the tool call."""
        mock_run.return_value = MagicMock(
            returncode=0, stdout="", stderr="",
        )

        # Configure a pre-tool-use hook
        self.hm._config.pre_tool_use = [{
            "matcher": "bash",
            "type": "command",
            "command": "echo ok",
            "timeout": 5,
        }]

        result = self.hm.run_pre_tool_use("bash", {"command": "ls"})
        self.assertTrue(result.allowed)
        mock_run.assert_called_once()

    @patch("brain.hooks.subprocess.run")
    def test_command_hook_block(self, mock_run):
        """Exit code 2 should block the tool call."""
        mock_run.return_value = MagicMock(
            returncode=2, stdout="", stderr="Blocked by policy",
        )

        self.hm._config.pre_tool_use = [{
            "matcher": "bash",
            "type": "command",
            "command": "check_policy.sh",
            "timeout": 5,
        }]

        result = self.hm.run_pre_tool_use("bash", {"command": "rm -rf /"})
        self.assertFalse(result.allowed)
        self.assertIn("Blocked", result.message)

    @patch("brain.hooks.subprocess.run")
    def test_command_hook_nonblocking_error(self, mock_run):
        """Exit code 1 (non-blocking error) should still allow."""
        mock_run.return_value = MagicMock(
            returncode=1, stdout="", stderr="warning",
        )

        self.hm._config.pre_tool_use = [{
            "matcher": "bash",
            "type": "command",
            "command": "warn.sh",
            "timeout": 5,
        }]

        result = self.hm.run_pre_tool_use("bash", {"command": "ls"})
        self.assertTrue(result.allowed)

    @patch("brain.hooks.subprocess.run")
    def test_hook_timeout(self, mock_run):
        """A hanging hook should time out and allow (non-blocking timeout).

        The timeout message is generated by _run_command_hook but since
        allowed=True, _run_hooks does not propagate it to the final result.
        We test _run_command_hook directly to verify the timeout path.
        """
        import subprocess
        mock_run.side_effect = subprocess.TimeoutExpired(cmd="slow.sh", timeout=5)

        entry = {
            "matcher": "bash",
            "type": "command",
            "command": "slow.sh",
            "timeout": 5,
        }

        # Test the internal method directly to verify timeout handling
        result = self.hm._run_command_hook(entry, "bash", {"command": "ls"}, "PreToolUse", "")
        self.assertTrue(result.allowed)
        self.assertIn("timed out", result.message.lower())

        # Also verify via run_pre_tool_use that execution is non-blocking
        self.hm._config.pre_tool_use = [entry]
        result = self.hm.run_pre_tool_use("bash", {"command": "ls"})
        self.assertTrue(result.allowed)

    @patch("brain.hooks.subprocess.run")
    def test_hook_returns_modified_args(self, mock_run):
        """A hook returning JSON with tool_input should modify args."""
        import json
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout=json.dumps({"tool_input": {"command": "ls -la"}}),
            stderr="",
        )

        self.hm._config.pre_tool_use = [{
            "matcher": "bash",
            "type": "command",
            "command": "sanitize.sh",
            "timeout": 5,
        }]

        result = self.hm.run_pre_tool_use("bash", {"command": "ls"})
        self.assertTrue(result.allowed)

    def test_matcher_skips_nonmatching(self):
        """Hooks with a non-matching matcher should be skipped entirely."""
        self.hm._config.pre_tool_use = [{
            "matcher": "edit_file",
            "type": "command",
            "command": "should_not_run.sh",
            "timeout": 5,
        }]

        # Running for "bash" should skip the edit_file hook and allow
        result = self.hm.run_pre_tool_use("bash", {"command": "ls"})
        self.assertTrue(result.allowed)


class TestHooksSummary(unittest.TestCase):
    """Test the summary() method."""

    def test_summary_empty(self):
        hm = HooksManager()
        s = hm.summary()
        self.assertEqual(s["pre_tool_use"], 0)
        self.assertEqual(s["post_tool_use"], 0)
        self.assertEqual(s["stop"], 0)
        self.assertFalse(s["skill_hooks_active"])

    def test_summary_with_hooks(self):
        hm = HooksManager()
        hm._config.pre_tool_use = [{"command": "a"}, {"command": "b"}]
        hm._config.post_tool_use = [{"command": "c"}]
        s = hm.summary()
        self.assertEqual(s["pre_tool_use"], 2)
        self.assertEqual(s["post_tool_use"], 1)

    def test_skill_hooks(self):
        hm = HooksManager()
        hm.set_skill_hooks({"PreToolUse": [{"command": "x"}]})
        self.assertTrue(hm.has_hooks)
        self.assertTrue(hm.summary()["skill_hooks_active"])
        hm.clear_skill_hooks()
        self.assertFalse(hm.has_hooks)


if __name__ == "__main__":
    unittest.main()
