package com.jarvis.android.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A single message in a [ConversationEntity].
 *
 * ## Role / content-type matrix
 *
 * | role        | contentType   | meaning                                           |
 * |-------------|---------------|---------------------------------------------------|
 * | user        | text          | Plain user input                                  |
 * | user        | tool_result   | Tool execution results returned to the model      |
 * | user        | image         | Camera frame or screenshot sent to the model      |
 * | assistant   | text          | Claude's text response                            |
 * | assistant   | tool_use      | Claude decided to call one or more tools          |
 * | assistant   | mixed         | Text + tool_use blocks in the same turn           |
 *
 * ## Tool call storage
 * When [contentType] is `tool_use` or `mixed`, [toolCallsJson] holds a JSON
 * array of serialised [ToolUseBlock] objects so the conversation can be
 * replayed without re-querying the API.
 *
 * ## Append-only WAL
 * Messages are never updated after insertion. The table uses a foreign key
 * to [ConversationEntity] with `CASCADE` delete so killing a conversation
 * wipes all its messages automatically.
 */
@Entity(
    tableName = "messages",
    foreignKeys = [
        ForeignKey(
            entity        = ConversationEntity::class,
            parentColumns = ["id"],
            childColumns  = ["conversation_id"],
            onDelete      = ForeignKey.CASCADE,
        )
    ],
    indices = [
        Index("conversation_id"),
        Index("timestamp"),
    ],
)
data class MessageEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /** Foreign key linking this message to its parent conversation. */
    @ColumnInfo(name = "conversation_id")
    val conversationId: String,

    /** `"user"` or `"assistant"`. */
    val role: String,

    /**
     * Primary text content of the message. For `tool_use` turns this holds
     * any prefacing text Claude wrote before the tool calls.
     */
    val content: String,

    /**
     * Describes the primary content type of this message row.
     * One of: `"text"`, `"tool_use"`, `"tool_result"`, `"image"`, `"mixed"`.
     */
    @ColumnInfo(name = "content_type")
    val contentType: String = "text",

    /**
     * JSON array of tool_use or tool_result blocks, serialised as a string.
     * Null when [contentType] is plain `"text"` or `"image"`.
     *
     * Shape for tool_use entries:
     * ```json
     * [{"id":"toolu_01...","name":"bash_exec","input":{"command":"ls /"}]
     * ```
     * Shape for tool_result entries:
     * ```json
     * [{"tool_use_id":"toolu_01...","content":"exit_code: 0\n...","is_error":false}]
     * ```
     */
    @ColumnInfo(name = "tool_calls_json")
    val toolCallsJson: String? = null,

    /** Unix epoch millis when this message was created / received. */
    val timestamp: Long = System.currentTimeMillis(),

    /** Input tokens consumed by this turn (assistant messages only). */
    @ColumnInfo(name = "input_tokens")
    val inputTokens: Int = 0,

    /** Output tokens generated by this turn (assistant messages only). */
    @ColumnInfo(name = "output_tokens")
    val outputTokens: Int = 0,

    /**
     * The model's stated reason for stopping: `"end_turn"`, `"tool_use"`,
     * `"max_tokens"`, or null for user messages.
     */
    @ColumnInfo(name = "stop_reason")
    val stopReason: String? = null,

    /**
     * True when the message was generated while the app was offline (using
     * a cached response or a local model relay). Shown with a badge in the UI.
     */
    @ColumnInfo(name = "is_offline")
    val isOffline: Boolean = false,
)
