"""Layout node adapter interface (Yoga-like)."""

from __future__ import annotations

from typing import Any, Callable, Literal


class LayoutEdge:
    All = "all"
    Horizontal = "horizontal"
    Vertical = "vertical"
    Left = "left"
    Right = "right"
    Top = "top"
    Bottom = "bottom"
    Start = "start"
    End = "end"


class LayoutGutter:
    All = "all"
    Column = "column"
    Row = "row"


class LayoutDisplay:
    Flex = "flex"
    No = "none"


class LayoutFlexDirection:
    Row = "row"
    RowReverse = "row-reverse"
    Column = "column"
    ColumnReverse = "column-reverse"


class LayoutAlign:
    Auto = "auto"
    Stretch = "stretch"
    FlexStart = "flex-start"
    Center = "center"
    FlexEnd = "flex-end"


class LayoutJustify:
    FlexStart = "flex-start"
    Center = "center"
    FlexEnd = "flex-end"
    SpaceBetween = "space-between"
    SpaceAround = "space-around"
    SpaceEvenly = "space-evenly"


class LayoutWrap:
    NoWrap = "nowrap"
    Wrap = "wrap"
    WrapReverse = "wrap-reverse"


class LayoutPositionType:
    Relative = "relative"
    Absolute = "absolute"


class LayoutOverflow:
    Visible = "visible"
    Hidden = "hidden"
    Scroll = "scroll"


LayoutMeasureMode = Literal["undefined", "exactly", "at-most"]


class LayoutNode:
    """Abstract layout node interface."""

    def set_width(self, width: float) -> None: ...
    def set_height(self, height: float) -> None: ...
    def set_width_auto(self) -> None: ...
    def set_height_auto(self) -> None: ...
    def set_width_percent(self, percent: float) -> None: ...
    def set_height_percent(self, percent: float) -> None: ...
    def set_min_width(self, width: float) -> None: ...
    def set_min_height(self, height: float) -> None: ...
    def set_max_width(self, width: float) -> None: ...
    def set_max_height(self, height: float) -> None: ...
    def set_min_width_percent(self, percent: float) -> None: ...
    def set_min_height_percent(self, percent: float) -> None: ...
    def set_max_width_percent(self, percent: float) -> None: ...
    def set_max_height_percent(self, percent: float) -> None: ...
    def set_flex_grow(self, grow: float) -> None: ...
    def set_flex_shrink(self, shrink: float) -> None: ...
    def set_flex_basis(self, basis: float) -> None: ...
    def set_flex_basis_percent(self, percent: float) -> None: ...
    def set_flex_direction(self, direction: str) -> None: ...
    def set_flex_wrap(self, wrap: str) -> None: ...
    def set_align_items(self, align: str) -> None: ...
    def set_align_self(self, align: str) -> None: ...
    def set_justify_content(self, justify: str) -> None: ...
    def set_display(self, display: str) -> None: ...
    def set_overflow(self, overflow: str) -> None: ...
    def set_position_type(self, position: str) -> None: ...
    def set_position(self, edge: str, value: float) -> None: ...
    def set_position_percent(self, edge: str, percent: float) -> None: ...
    def set_margin(self, edge: str, value: float) -> None: ...
    def set_padding(self, edge: str, value: float) -> None: ...
    def set_border(self, edge: str, value: float) -> None: ...
    def set_gap(self, gutter: str, value: float) -> None: ...
    def set_measure_func(self, func: Callable) -> None: ...
    def mark_dirty(self) -> None: ...
    def insert_child(self, child: LayoutNode, index: int) -> None: ...
    def remove_child(self, child: LayoutNode) -> None: ...
    def get_child_count(self) -> int: ...
    def calculate_layout(self, width: float, height: float) -> None: ...
    def get_computed_width(self) -> float: ...
    def get_computed_height(self) -> float: ...
    def get_computed_top(self) -> float: ...
    def get_computed_left(self) -> float: ...
    def get_computed_right(self) -> float: ...
    def get_computed_bottom(self) -> float: ...
    def get_computed_padding(self, edge: str) -> float: ...
    def get_computed_border(self, edge: str) -> float: ...
    def get_computed_margin(self, edge: str) -> float: ...
    def get_display(self) -> str: ...
    def free(self) -> None: ...
    def free_recursive(self) -> None: ...
