# JARVIS Constants package -- converted from TypeScript
# Re-exports key constants for convenience

from .system import DEFAULT_PREFIX, AGENT_SDK_PREFIX, get_cli_sysprompt_prefix
from .product import PRODUCT_URL
from .prompts import FRONTIER_MODEL_NAME, get_hooks_section, get_actions_section
from .figures import (
    BLACK_CIRCLE, LIGHTNING_BOLT, EFFORT_LOW, EFFORT_MEDIUM, EFFORT_HIGH, EFFORT_MAX,
    PLAY_ICON, PAUSE_ICON, BLOCKQUOTE_BAR, HEAVY_HORIZONTAL,
    DIAMOND_OPEN, DIAMOND_FILLED, REFERENCE_MARK, FLAG_ICON,
    REFRESH_ARROW, FORK_GLYPH,
)
from .tools import (
    BASH_TOOL_NAME, FILE_READ_TOOL_NAME, FILE_WRITE_TOOL_NAME,
    FILE_EDIT_TOOL_NAME, GREP_TOOL_NAME, GLOB_TOOL_NAME,
    WEB_SEARCH_TOOL_NAME, WEB_FETCH_TOOL_NAME, AGENT_TOOL_NAME,
    ALL_AGENT_DISALLOWED_TOOLS, ASYNC_AGENT_ALLOWED_TOOLS,
)
