"""JARVIS behavioral log analyzer.

Reads recent conversation turns from ~/.jarvis/conversations.db and the
agent log file to identify repeated behavioral failure patterns. Writes
candidate rules to ~/.jarvis/learned_rules.proposals.md for human review.

Never modifies learned_rules.md directly — only proposals.md.
All errors are caught; this module must never crash the agent.

Entry point: await run_analysis() from entrypoint() as a background task.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import sqlite3
import time
import urllib.error
import urllib.request
from pathlib import Path

logger = logging.getLogger("jarvis.log_analyzer")

CONVO_DB_PATH   = Path.home() / ".jarvis" / "conversations.db"
TELEMETRY_DB_PATH = Path.home() / ".local" / "share" / "jarvis" / "turn_telemetry.db"
RULES_PATH      = Path.home() / ".jarvis" / "learned_rules.md"
PROPOSALS_PATH  = Path.home() / ".jarvis" / "learned_rules.proposals.md"
AGENT_LOG_PATH  = Path("/tmp/jarvis-voice-agent.log")

ANALYSIS_COOLDOWN_H = 12   # minimum hours between analysis runs
LOOKBACK_DAYS       = 7    # how far back to read from the DB

QUIET_HOURS_START = int(os.environ.get("JARVIS_QUIET_START", "23"))
QUIET_HOURS_END   = int(os.environ.get("JARVIS_QUIET_END",   "7"))

# Words in a user turn that indicate a correction JARVIS missed
_CORRECTION_WORDS = [
    "that was wrong", "you keep doing", "don't do that", "never do that",
    "stop doing", "why did you", "that's not what", "didn't ask you to",
    "i didn't say", "you got it wrong", "that's incorrect", "you're wrong",
    "don't open", "don't play", "don't start", "i never asked",
]


def _in_quiet_hours(ts: int) -> bool:
    hour = time.localtime(ts).tm_hour
    if QUIET_HOURS_START > QUIET_HOURS_END:
        return hour >= QUIET_HOURS_START or hour < QUIET_HOURS_END
    return QUIET_HOURS_START <= hour < QUIET_HOURS_END


def _should_run() -> bool:
    """True if enough time has elapsed since the last analysis."""
    if not PROPOSALS_PATH.exists():
        return True
    try:
        age_s = time.time() - PROPOSALS_PATH.stat().st_mtime
        return age_s > ANALYSIS_COOLDOWN_H * 3600
    except Exception:
        return True


def _load_existing_proposals() -> list[dict]:
    """Parse proposals.md into a list of dicts. Empty list on any error."""
    if not PROPOSALS_PATH.exists():
        return []
    try:
        content = PROPOSALS_PATH.read_text(encoding="utf-8")
        proposals = []
        for block in re.split(r"(?m)^## Proposal \d+", content):
            block = block.strip()
            if not block:
                continue
            status_m = re.search(r"\[(PENDING|ACCEPTED|REJECTED)\]", block)
            # Skip header/preamble blocks that have no status marker
            if not status_m:
                continue
            date_m = re.search(r"\[(\d{4}-\d{2}-\d{2})\]", block)
            rule_m = re.search(r"\*\*Proposed rule:\*\*\s*(.+?)(?:\n|$)", block)
            pat_m  = re.search(r"\*\*Pattern:\*\*\s*(.+?)(?:\n|$)", block)
            ev_m   = re.search(r"\*\*Evidence:\*\*\s*(.+?)(?:\n|$)", block)
            rule = rule_m.group(1).strip() if rule_m else ""
            # Skip proposals with no rule text (malformed blocks)
            if not rule:
                continue
            proposals.append({
                "status":   status_m.group(1),
                "date":     date_m.group(1) if date_m else "",
                "rule":     rule,
                "pattern":  pat_m.group(1).strip() if pat_m else "",
                "evidence": ev_m.group(1).strip()  if ev_m  else "",
            })
        return proposals
    except Exception:
        return []


def _write_proposals(proposals: list[dict]) -> None:
    """Serialize proposals list back to proposals.md."""
    PROPOSALS_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "# JARVIS Pending Rule Proposals\n\n",
        "<!-- Generated by tools.log_analyzer. -->\n",
        "<!-- Review with: 'Jarvis, review pending rules' -->\n\n",
    ]
    for i, p in enumerate(proposals, 1):
        lines.append(f"## Proposal {i} [{p.get('date', '')}] [{p.get('status', 'PENDING')}]\n")
        if p.get("pattern"):
            lines.append(f"**Pattern:** {p['pattern']}\n")
        if p.get("evidence"):
            lines.append(f"**Evidence:** {p['evidence']}\n")
        lines.append(f"**Proposed rule:** {p['rule']}\n\n")
    PROPOSALS_PATH.write_text("".join(lines), encoding="utf-8")


def _gather_evidence() -> dict:
    """
    Collect behavioral signals from conversations.db and the agent log.
    Blocking — call via asyncio.to_thread.
    """
    cutoff = int(time.time()) - LOOKBACK_DAYS * 86400
    ev: dict = {
        "night_responses": [],     # JARVIS replied during quiet hours
        "night_user_turns": [],    # user turns during quiet hours
        "correction_turns": [],    # user expressing corrections
        "log_snippets": "",        # relevant log lines
    }

    # ── conversations.db ─────────────────────────────────────────────
    if CONVO_DB_PATH.exists():
        try:
            with sqlite3.connect(str(CONVO_DB_PATH), timeout=2.0) as conn:
                rows = conn.execute(
                    "SELECT ts, role, text FROM turns "
                    "WHERE ts >= ? AND role IN ('user','assistant') "
                    "ORDER BY ts ASC",
                    (cutoff,),
                ).fetchall()
        except Exception as e:
            logger.warning(f"[analyzer] db read failed: {e}")
            rows = []

        for ts, role, text in rows:
            text = (text or "").strip()
            if not text:
                continue
            stamp = time.strftime("%Y-%m-%d %H:%M", time.localtime(ts))
            is_night = _in_quiet_hours(ts)

            if role == "assistant" and is_night:
                ev["night_responses"].append(f"{stamp}: {text[:120]}")

            if role == "user":
                if is_night:
                    ev["night_user_turns"].append(f"{stamp}: {text[:120]}")
                low = text.lower()
                if any(w in low for w in _CORRECTION_WORDS):
                    ev["correction_turns"].append(f"{stamp} [user]: {text[:160]}")

    # ── Agent log tail ────────────────────────────────────────────────
    if AGENT_LOG_PATH.exists():
        try:
            size = AGENT_LOG_PATH.stat().st_size
            with AGENT_LOG_PATH.open("rb") as f:
                f.seek(max(0, size - 40_000))
                tail = f.read().decode("utf-8", errors="replace")

            interesting: list[str] = []
            for line in tail.splitlines():
                if any(k in line for k in (
                    "quiet-hours", "silent-mode", "TTS error", "TTS bad",
                    "TTS rate", "chain limit", "dropping ambient",
                    "mute phrase", "media_control", "run_jarvis_cli",
                    "stale lock", "watchdog",
                )):
                    interesting.append(line[-220:])
            ev["log_snippets"] = "\n".join(interesting[-100:])
        except Exception as e:
            logger.warning(f"[analyzer] log read failed: {e}")

    return ev


def _gather_telemetry_evidence(lookback_days: int = LOOKBACK_DAYS) -> dict:
    """Mine `turn_telemetry.db` for evolution-relevant signals.

    The previous evidence source (`conversations.db`) is unreliable —
    it has been zero-byte since 2026-05-04 in production. Telemetry is
    written on every turn by `pipeline/turn_telemetry.py`, so this is
    the live source.

    Signals returned (4):
      - correction_turns: user phrases like "stop doing", "you're wrong"
      - interrupted_turns: turns flagged interrupted=1 in telemetry
      - route_fallback_turns: turns where route_fallback fired
      - hard_pressure_turns: turns at context_pressure='hard'
    """
    ev: dict = {
        "correction_turns": [],
        "interrupted_turns": [],
        "route_fallback_turns": [],
        "hard_pressure_turns": [],
    }
    if not TELEMETRY_DB_PATH.exists():
        return ev
    cutoff_iso = time.strftime(
        "%Y-%m-%dT%H:%M:%SZ",
        time.gmtime(time.time() - lookback_days * 86400),
    )
    try:
        with sqlite3.connect(str(TELEMETRY_DB_PATH), timeout=2.0) as conn:
            rows = conn.execute(
                "SELECT ts_utc, user_text, jarvis_text, route, interrupted, "
                "       route_fallback, context_pressure "
                "FROM turns WHERE ts_utc >= ? ORDER BY ts_utc ASC",
                (cutoff_iso,),
            ).fetchall()
    except Exception as e:
        logger.warning(f"[analyzer] telemetry read failed: {e}")
        return ev

    for ts, utext, jtext, route, interrupted, rfb, pressure in rows:
        utext = (utext or "").strip()
        jtext = (jtext or "").strip()
        if not utext and not jtext:
            continue
        label = f"{ts} [{route or '?'}]"

        low_u = utext.lower()
        if any(w in low_u for w in _CORRECTION_WORDS):
            ev["correction_turns"].append(f"{label} user: {utext[:160]}")
        if interrupted:
            ev["interrupted_turns"].append(f"{label} user: {utext[:120]}")
        if rfb:
            ev["route_fallback_turns"].append(f"{label} user: {utext[:120]}")
        if pressure == "hard":
            ev["hard_pressure_turns"].append(f"{label} user: {utext[:120]}")
    return ev


def _call_llm_for_proposals(ev: dict) -> list[dict]:
    """
    Submit evidence to Groq, parse the JSON response into proposal dicts.
    Blocking — call via asyncio.to_thread.
    Returns [] on any failure.
    """
    api_key = os.environ.get("GROQ_API_KEY", "")
    if not api_key:
        logger.warning("[analyzer] GROQ_API_KEY not set — skipping LLM analysis")
        return []

    # Skip if there's nothing interesting to analyze
    has_signal = (
        ev["night_responses"]
        or ev["correction_turns"]
        or (ev["log_snippets"] and len(ev["log_snippets"]) > 50)
    )
    if not has_signal:
        logger.info("[analyzer] no meaningful signal in evidence — skipping LLM call")
        return []

    existing_rules = ""
    try:
        if RULES_PATH.exists():
            existing_rules = RULES_PATH.read_text(encoding="utf-8").strip()
    except Exception:
        pass

    def _fmt(items: list[str], n: int = 8) -> str:
        return "\n".join(items[:n]) if items else "(none)"

    evidence_text = "\n\n".join(filter(None, [
        f"JARVIS responses during quiet hours ({len(ev['night_responses'])} total):\n"
        + _fmt(ev["night_responses"])
        if ev["night_responses"] else "",

        f"User turns during quiet hours ({len(ev['night_user_turns'])} total):\n"
        + _fmt(ev["night_user_turns"])
        if ev["night_user_turns"] else "",

        f"User correction turns ({len(ev['correction_turns'])} total):\n"
        + _fmt(ev["correction_turns"])
        if ev["correction_turns"] else "",

        f"Relevant log lines:\n{ev['log_snippets'][:2500]}"
        if ev["log_snippets"] else "",
    ]))

    prompt = (
        "You are analyzing a voice assistant's (JARVIS) behavioral logs "
        "to identify specific, recurring mistakes worth turning into "
        "permanent behavioral rules.\n\n"
        "JARVIS runs 24/7 on a Linux laptop with an always-on mic. Its "
        "main failure modes: acting on ambient household noise as commands, "
        "being too chatty after tool calls, and doing things at night.\n\n"
        f"Already-learned rules (do not re-propose):\n{existing_rules or '(none yet)'}\n\n"
        f"Evidence (last {LOOKBACK_DAYS} days):\n{evidence_text}\n\n"
        "Identify up to 3 SPECIFIC recurring problems with clear evidence. "
        "For each:\n"
        "- pattern: one sentence describing the failure pattern\n"
        "- evidence: specific timestamps or log lines that show it happened\n"
        "- rule: a concrete ≤120-char behavioral rule that would prevent it\n\n"
        "Respond with ONLY a JSON array of objects with keys: "
        "pattern, evidence, rule. "
        "If there are no clear problems, respond with []."
    )

    payload = {
        "model": "llama-3.1-8b-instant",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.2,
        "max_tokens": 600,
    }

    try:
        req = urllib.request.Request(
            "https://api.groq.com/openai/v1/chat/completions",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "User-Agent": "python-urllib/3 jarvis-analyzer/1.0",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            result = json.loads(resp.read().decode("utf-8"))

        raw = result["choices"][0]["message"]["content"].strip()
        # Strip optional markdown fences
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)

        parsed = json.loads(raw)
        if not isinstance(parsed, list):
            return []

        today = time.strftime("%Y-%m-%d")
        proposals: list[dict] = []
        for item in parsed[:3]:
            if not isinstance(item, dict) or not item.get("rule"):
                continue
            proposals.append({
                "status":   "PENDING",
                "date":     today,
                "pattern":  str(item.get("pattern") or "")[:200],
                "evidence": str(item.get("evidence") or "")[:200],
                "rule":     str(item.get("rule") or "")[:200],
            })
        return proposals

    except urllib.error.URLError as e:
        logger.warning(f"[analyzer] Groq API error: {e}")
    except (json.JSONDecodeError, KeyError) as e:
        logger.warning(f"[analyzer] LLM response parse error: {e}")
    except Exception as e:
        logger.warning(f"[analyzer] unexpected error: {e}")
    return []


async def run_analysis() -> int:
    """
    Entry point — called from entrypoint() as a background asyncio task.
    Returns the number of newly staged proposals (0 on skip or error).
    All exceptions are caught; this function never raises.
    """
    if not _should_run():
        logger.info("[analyzer] cooldown active — skipping")
        return 0

    logger.info("[analyzer] starting behavioral log analysis")
    try:
        ev       = await asyncio.to_thread(_gather_evidence)
        new_raw  = await asyncio.to_thread(_call_llm_for_proposals, ev)

        # Ensure proposals file exists (touch to reset cooldown timer)
        PROPOSALS_PATH.parent.mkdir(parents=True, exist_ok=True)
        if not PROPOSALS_PATH.exists():
            PROPOSALS_PATH.write_text(
                "# JARVIS Pending Rule Proposals\n\n(No proposals yet.)\n",
                encoding="utf-8",
            )

        if not new_raw:
            logger.info("[analyzer] no new proposals generated")
            PROPOSALS_PATH.touch()  # reset cooldown even with no proposals
            return 0

        # Deduplicate against existing pending proposals
        existing = [p for p in _load_existing_proposals()
                    if p.get("status") == "PENDING"]
        existing_rules_lc = {p["rule"].lower() for p in existing}
        truly_new = [p for p in new_raw
                     if p["rule"].lower() not in existing_rules_lc]

        if not truly_new:
            logger.info("[analyzer] all proposed rules already pending")
            PROPOSALS_PATH.touch()
            return 0

        all_proposals = existing + truly_new
        await asyncio.to_thread(_write_proposals, all_proposals)
        logger.info(
            f"[analyzer] staged {len(truly_new)} new proposal(s) "
            f"→ {PROPOSALS_PATH}"
        )
        return len(truly_new)

    except Exception as e:
        logger.warning(f"[analyzer] analysis failed: {e}")
        return 0


def count_pending() -> int:
    """Return the number of PENDING proposals. 0 on any error."""
    try:
        return sum(1 for p in _load_existing_proposals()
                   if p.get("status") == "PENDING")
    except Exception:
        return 0
