##──────────────────────────────────────────────────────────────────────────────
## JARVIS Android — ProGuard / R8 rules
## Applied to release builds only (debug is unminified).
## Keep rules are conservative: we preserve names/signatures that are
## accessed reflectively or via external contracts (JSON, JNI, Room, etc.)
##──────────────────────────────────────────────────────────────────────────────


##──────────────────────────────────────────────────────────────────────────────
## 1. GENERAL ANDROID FRAMEWORK
##──────────────────────────────────────────────────────────────────────────────

# Keep line numbers for crash-stack readability (mapping file uploaded separately)
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# Keep all annotations — many frameworks read them at runtime
-keepattributes *Annotation*

# Keep generic signatures (needed by Retrofit, kotlinx.serialization, Room)
-keepattributes Signature

# Keep inner-class relationships (required by Hilt and Compose internals)
-keepattributes InnerClasses,EnclosingMethod

# Standard Android entry points — never strip
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference

# Parcelable CREATOR fields (used by Android IPC)
-keepclassmembers class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}

# Enum valueOf / values are accessed reflectively by Android framework
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}


##──────────────────────────────────────────────────────────────────────────────
## 2. KOTLIN
##──────────────────────────────────────────────────────────────────────────────

# Kotlin metadata — needed by kotlinx.serialization and coroutines
-keep class kotlin.Metadata { *; }
-keepclassmembers class kotlin.Metadata { *; }

# Kotlin coroutines internals accessed by reflection
-keepclassmembers class kotlinx.coroutines.** {
    volatile <fields>;
}
-keepclassmembers class kotlin.coroutines.** {
    volatile <fields>;
}
-keep class kotlinx.coroutines.android.AndroidExceptionPreHandler { *; }
-keep class kotlinx.coroutines.android.AndroidDispatcherFactory { *; }

# Kotlin stdlib — JVM intrinsics
-dontwarn kotlin.**
-dontnote kotlin.**


##──────────────────────────────────────────────────────────────────────────────
## 3. KOTLINX.SERIALIZATION
##──────────────────────────────────────────────────────────────────────────────

# Serialization plugin generates companion objects that R8 may strip
-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class * {
    @kotlinx.serialization.Serializable <fields>;
}

# Keep all @Serializable classes in our package (DTOs, domain models)
-keep @kotlinx.serialization.Serializable class com.jarvis.android.** { *; }

# Serializer companion objects generated by the plugin
-keepclassmembers @kotlinx.serialization.Serializable class * {
    static ** $serializer;
    *** Companion;
    *** INSTANCE;
    kotlinx.serialization.KSerializer serializer(...);
}

-dontwarn kotlinx.serialization.**


##──────────────────────────────────────────────────────────────────────────────
## 4. RETROFIT 2 + OKHTTP
##──────────────────────────────────────────────────────────────────────────────

# Retrofit uses reflection on service interface methods and their annotations
-keep,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.* <methods>;
}

# Response / request model fields accessed by Gson/Kotlin Serialization converters
-keepclassmembers class com.jarvis.android.data.api.dto.** { *; }

# OkHttp platform detection (uses reflection to detect Android version)
-dontwarn okhttp3.**
-dontwarn okio.**
-dontnote okhttp3.**
-keep class okhttp3.internal.platform.** { *; }
-keep class okhttp3.EventListener { *; }
-keep class okhttp3.EventListener$Factory { *; }

# SSE EventSource
-keep class okhttp3.sse.** { *; }


##──────────────────────────────────────────────────────────────────────────────
## 5. HILT / DAGGER
##──────────────────────────────────────────────────────────────────────────────

# Hilt generates Dagger components — all generated classes must survive
-keep class dagger.hilt.** { *; }
-keep class javax.inject.** { *; }
-keep class * extends dagger.hilt.android.internal.managers.** { *; }

# Hilt entry points (used by AndroidEntryPoint-annotated classes)
-keepclasseswithmembers class * {
    @dagger.hilt.android.AndroidEntryPoint <init>(...);
}
-keepclasseswithmembers class * {
    @dagger.hilt.InstallIn *;
}

# Hilt ViewModel injection
-keepclasseswithmembers class * extends androidx.lifecycle.ViewModel {
    <init>(...);
}

-dontwarn dagger.**
-dontnote dagger.**


##──────────────────────────────────────────────────────────────────────────────
## 6. ROOM
##──────────────────────────────────────────────────────────────────────────────

# Room generates implementation classes at compile time — keep the contracts
-keep class * extends androidx.room.RoomDatabase { *; }
-keep @androidx.room.Entity class * { *; }
-keep @androidx.room.Dao interface * { *; }
-keep @androidx.room.TypeConverter class * { *; }

# Room's InvalidationTracker uses reflection on table names
-keepclassmembers class * extends androidx.room.RoomDatabase {
    abstract ** getOpenHelper();
}

-dontwarn androidx.room.**


##──────────────────────────────────────────────────────────────────────────────
## 7. DATASTORE / PROTOBUF
##──────────────────────────────────────────────────────────────────────────────

# Protobuf lite uses field-level reflection for serialization
-keep class * extends com.google.protobuf.GeneratedMessageLite { *; }
-keep class com.google.protobuf.** { *; }
-keepclassmembers class * extends com.google.protobuf.** {
    <fields>;
    <methods>;
}

-dontwarn com.google.protobuf.**

# DataStore serializer interface implementations must not be renamed
-keep class * implements androidx.datastore.core.Serializer { *; }


##──────────────────────────────────────────────────────────────────────────────
## 8. SECURITY / CRYPTO
##──────────────────────────────────────────────────────────────────────────────

# EncryptedSharedPreferences accesses KeyStore via reflection
-keep class androidx.security.crypto.** { *; }
-dontwarn androidx.security.crypto.**

# CRITICAL: API key class — never log, never obfuscate in a traceable way.
# The class itself can be renamed but the *contents* must never appear in logs.
# (Enforced in code — this rule is belt-and-suspenders.)
-keepclassmembers class com.jarvis.android.core.network.ApiKeyInterceptor {
    private final java.lang.String apiKey;
}


##──────────────────────────────────────────────────────────────────────────────
## 9. LIBSU (Root Shell)
##──────────────────────────────────────────────────────────────────────────────

# libsu RootService uses IPC/Binder reflection internally
-keep class com.topjohnwu.superuser.** { *; }
-keepclassmembers class * extends com.topjohnwu.superuser.ipc.RootService {
    <init>();
}
-dontwarn com.topjohnwu.superuser.**


##──────────────────────────────────────────────────────────────────────────────
## 10. JNI BRIDGE (PTY / VT Parser)
##──────────────────────────────────────────────────────────────────────────────

# JNI methods must keep their exact names — the native layer looks them up by
# the JNI name mangling convention (Java_com_jarvis_android_system_terminal_*)
-keepclasseswithmembernames class com.jarvis.android.system.terminal.PtyManager {
    native <methods>;
}
-keepclasseswithmembernames class com.jarvis.android.system.terminal.VtParser {
    native <methods>;
}


##──────────────────────────────────────────────────────────────────────────────
## 11. MARKWON + PRISM4J
##──────────────────────────────────────────────────────────────────────────────

# Prism4j-bundler generates language grammar classes via annotation processing;
# the resulting classes are loaded by class name at runtime
-keep class io.noties.prism4j.annotations.** { *; }
-keep class **_Prism4jBundler { *; }   # generated bundler class
-keep class io.noties.prism4j.** { *; }
-keep class io.noties.markwon.** { *; }

-dontwarn io.noties.**


##──────────────────────────────────────────────────────────────────────────────
## 12. COIL 3
##──────────────────────────────────────────────────────────────────────────────

-keep class coil3.** { *; }
-dontwarn coil3.**


##──────────────────────────────────────────────────────────────────────────────
## 13. OSMDROID (OpenStreetMap)
##──────────────────────────────────────────────────────────────────────────────

-keep class org.osmdroid.** { *; }
-dontwarn org.osmdroid.**


##──────────────────────────────────────────────────────────────────────────────
## 14. CAMERAX
##──────────────────────────────────────────────────────────────────────────────

-keep class androidx.camera.** { *; }
-dontwarn androidx.camera.**


##──────────────────────────────────────────────────────────────────────────────
## 15. GOOGLE PLAY SERVICES (Location only)
##──────────────────────────────────────────────────────────────────────────────

-keep class com.google.android.gms.location.** { *; }
-dontwarn com.google.android.gms.**


##──────────────────────────────────────────────────────────────────────────────
## 16. COMPOSE
##──────────────────────────────────────────────────────────────────────────────

# Compose runtime introspects lambda class names for tooling/tracing
-keep class androidx.compose.runtime.** { *; }
-keepclassmembers class androidx.compose.** {
    volatile <fields>;
}
-dontwarn androidx.compose.**


##──────────────────────────────────────────────────────────────────────────────
## 17. JARVIS APPLICATION LAYER
##──────────────────────────────────────────────────────────────────────────────

# Domain models used as tool_use JSON payloads — field names must match the
# JSON keys that Claude returns, so we cannot obfuscate them
-keep class com.jarvis.android.domain.model.** { *; }

# Tool dispatcher routes by tool name string — keep the routing map intact
-keep class com.jarvis.android.system.tools.JarvisToolDispatcher { *; }

# Android Services declared in the manifest — class names must be stable
-keep class com.jarvis.android.service.** extends android.app.Service { *; }
-keep class com.jarvis.android.service.JarvisNotificationListener { *; }
-keep class com.jarvis.android.service.JarvisAccessibilityService { *; }
-keep class com.jarvis.android.service.JarvisDeviceAdmin { *; }

# BroadcastReceiver for BOOT_COMPLETED
-keep class com.jarvis.android.** extends android.content.BroadcastReceiver { *; }


##──────────────────────────────────────────────────────────────────────────────
## 18. SUPPRESS NOISY WARNINGS FROM TRANSITIVE DEPS
##──────────────────────────────────────────────────────────────────────────────

-dontwarn javax.annotation.**
-dontwarn org.codehaus.mojo.**
-dontwarn sun.misc.Unsafe
-dontwarn java.lang.instrument.**
-dontwarn edu.umd.cs.findbugs.**
-dontwarn org.slf4j.**
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
