import { NextResponse } from "next/server";
import {
  getWorkspace,
  updateWorkspaceMeta,
  writeFile,
} from "@/lib/workspace/storage";

export const runtime = "nodejs";
export const maxDuration = 60;

/**
 * POST /api/workspace/[id]/auth/scaffold
 *
 * Writes next-auth v5 (Auth.js) boilerplate into the workspace based
 * on the provider config in workspace.auth. Files written:
 *
 *   - auth.ts                    Auth() factory + provider list
 *   - app/api/auth/[...nextauth]/route.ts  GET/POST handlers
 *   - middleware.ts              session-required gate
 *   - lib/db/users.ts            sqlite users + sessions schema helpers
 *
 * Idempotent — re-running with a different provider config just
 * overwrites the files. The user's own customizations to these files
 * WILL be lost on rescaffold; we surface that warning in the UI.
 *
 * Doesn't run installs / migrations — that's left to the user (or to
 * the chat AI on the next turn after they restart the runtime). The
 * response includes a list of npm deps the workspace will need to add
 * to package.json (next-auth, @auth/core, etc.) so the UI can show
 * the user a one-click "ask AI to install + wire" follow-up prompt.
 */

export async function POST(
  _req: Request,
  ctx: { params: Promise<{ id: string }> },
) {
  const { id } = await ctx.params;
  const ws = await getWorkspace(id);
  if (!ws) return NextResponse.json({ error: "not_found" }, { status: 404 });
  if (!ws.auth || ws.auth.providers.length === 0) {
    return NextResponse.json(
      {
        error: "no_providers",
        hint: "Enable at least one auth provider in Settings → Authentication, then scaffold.",
      },
      { status: 400 },
    );
  }

  const { providers, sessionMins, cookieSecure, cookieSameSite } = ws.auth;
  const usesCredentials = providers.includes("credentials");
  const usesMagicLink = providers.includes("magic-link");
  const usesGoogle = providers.includes("google");
  const usesGithub = providers.includes("github");

  const written: string[] = [];

  // ── auth.ts ────────────────────────────────────────────────────────
  const providerImports: string[] = [];
  const providerInstances: string[] = [];
  if (usesCredentials) {
    providerImports.push(
      `import Credentials from "next-auth/providers/credentials";`,
    );
    providerInstances.push(
      `  Credentials({
    credentials: {
      email: { label: "Email", type: "email" },
      password: { label: "Password", type: "password" },
    },
    async authorize(creds) {
      // TODO: replace with real verification against your users table.
      // The scaffold leaves this as a stub so dev can see the flow.
      const email = String(creds?.email ?? "").toLowerCase().trim();
      const password = String(creds?.password ?? "");
      if (!email || !password) return null;
      return { id: email, email, name: email.split("@")[0] };
    },
  })`,
    );
  }
  if (usesMagicLink) {
    providerImports.push(
      `import Email from "next-auth/providers/nodemailer";`,
    );
    providerInstances.push(
      `  Email({
    server: {
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT ?? 587),
      auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASSWORD },
    },
    from: process.env.SMTP_FROM,
  })`,
    );
  }
  if (usesGoogle) {
    providerImports.push(`import Google from "next-auth/providers/google";`);
    providerInstances.push(
      `  Google({ clientId: process.env.GOOGLE_CLIENT_ID!, clientSecret: process.env.GOOGLE_CLIENT_SECRET! })`,
    );
  }
  if (usesGithub) {
    providerImports.push(`import GitHub from "next-auth/providers/github";`);
    providerInstances.push(
      `  GitHub({ clientId: process.env.GITHUB_CLIENT_ID!, clientSecret: process.env.GITHUB_CLIENT_SECRET! })`,
    );
  }

  const authTs = `// Auto-generated by JARVIS Settings → Authentication. Re-running
// "Scaffold" overwrites this file — keep customizations in a separate
// file (e.g. auth.config.ts) and re-import here if you need them.
import NextAuth from "next-auth";
${providerImports.join("\n")}

export const { auth, handlers, signIn, signOut } = NextAuth({
  providers: [
${providerInstances.join(",\n")}
  ],
  session: {
    strategy: "jwt",
    maxAge: ${sessionMins * 60},
  },
  cookies: {
    sessionToken: {
      options: {
        httpOnly: true,
        sameSite: ${JSON.stringify(cookieSameSite)},
        secure: ${cookieSecure ? "true" : "false"},
        path: "/",
      },
    },
  },
});
`;
  await writeFile(id, "auth.ts", authTs);
  written.push("auth.ts");

  // ── app/api/auth/[...nextauth]/route.ts ────────────────────────────
  const handlerTs = `// Auto-generated by JARVIS Settings → Authentication.
import { handlers } from "@/auth";
export const { GET, POST } = handlers;
`;
  await writeFile(id, "app/api/auth/[...nextauth]/route.ts", handlerTs);
  written.push("app/api/auth/[...nextauth]/route.ts");

  // ── middleware.ts ─────────────────────────────────────────────────
  const middleware = `// Auto-generated by JARVIS Settings → Authentication.
// Gates every route under /protected by default. Adjust the matcher
// to fit your app's needs.
export { auth as middleware } from "@/auth";

export const config = {
  matcher: ["/protected/:path*"],
};
`;
  await writeFile(id, "middleware.ts", middleware);
  written.push("middleware.ts");

  // ── lib/db/users.ts ───────────────────────────────────────────────
  const usersTs = `// Auto-generated by JARVIS Settings → Authentication.
// Minimal users + sessions schema. Run \`bunx tsx lib/db/users.ts\` once
// to initialize the tables, or call initUsers() from your db setup.
import Database from "better-sqlite3";
import path from "node:path";

const DB_PATH = process.env.DATABASE_PATH ?? path.join(process.cwd(), "data/app.db");

export function initUsers() {
  const db = new Database(DB_PATH);
  db.exec(\`
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      name TEXT,
      password_hash TEXT,
      role TEXT NOT NULL DEFAULT 'user',
      created_at INTEGER NOT NULL DEFAULT (unixepoch()),
      updated_at INTEGER NOT NULL DEFAULT (unixepoch())
    );
    CREATE TABLE IF NOT EXISTS sessions (
      token TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at INTEGER NOT NULL,
      created_at INTEGER NOT NULL DEFAULT (unixepoch())
    );
    CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
  \`);
  db.close();
}

if (require.main === module) {
  initUsers();
  console.log("users + sessions tables initialized at", DB_PATH);
}
`;
  await writeFile(id, "lib/db/users.ts", usersTs);
  written.push("lib/db/users.ts");

  // Mark scaffolded so the UI shows "Scaffolded" instead of "Configure".
  await updateWorkspaceMeta(id, {
    auth: { ...ws.auth, scaffolded: true },
  });

  // Compute the npm deps the user needs to install.
  const deps = ["next-auth@beta", "@auth/core"];
  if (usesMagicLink) deps.push("nodemailer");
  if (usesCredentials || usesMagicLink) deps.push("better-sqlite3");

  return NextResponse.json({
    ok: true,
    written,
    deps,
    hint: `Run \`bun install ${deps.join(" ")}\` then \`bunx tsx lib/db/users.ts\` to initialize the schema. Add the OAuth client_id/secret env vars in Settings → Secrets.`,
  });
}
